### ISSUE TITLE
Cannot specify a subset of scopes in authorisation request

### ISSUE THREAD

**Issue by jnv** [cvut/zuul-oaas#12]
I am attempting to generate access token through Postman 2 with limited scopes. When I specify the requested scope in the Postman, few things may happen:

When I enter the only scope, e.g. `cvut:sirius:personal:read`, I get a prompt to authorise _all scopes_ associated with the client, i.e. I cannot authorise only a limited scope.

When I enter multiple coma separated scopes, e.g. `cvut:sirius:personal:read,urn:ctu:oauth:sirius:personal:read` I get a blank response; probably a server error. The same thing happens when I enter some random or invalid string.

**Comment by jirutka** [comment]
> When I enter multiple coma separated scopes…

Scopes must be **space** separated, not comma separated. See table on [this page](https://github.com/cvut/zuul-oaas/wiki/Authorization-Code-Grant#authorize).

**Comment by jirutka** [comment]
I’ve reproduced this issue even with single scope, so it’s not problem with a separator.
